# 网站基本信息
title: 孙林林 - 个人主页
description: 欢迎访问孙林林的个人主页
theme: minima

# 导航栏配置
navbar:
  - name: 简历
    url: /#简历
  - name: 论文
    url: /#论文
  - name: 项目
    url: /#项目
  - name: 其他
    url: /#其他

# 页脚配置
footer:
  copyright: "©2025 孙林林"
  address: "湖南省湘潭市湘潭大学数学与计算科学学院"
  postal_code: "411105"
  contact: "邮箱: sunll@xtu.edu.cn | ORCID: [0000-0002-8842-2296](https://orcid.org/0000-0002-8842-2296)"
